### ISSUE TITLE
Pip install fail 

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#3] opened 2021-02-10 11:03 UTC
* mt2 version: 0.1.4
* Python version: 3.7.6
* Operating System: macOS Catalina, version 10.15.7

### Description

Pip install fails.

### What I Did

```
Will Fawcett  10:56 AM
okay, I removed the old version of mt2 (from the git package) and tried again, unfortunately I the pip install doesn’t seem to work:
$ pip install mt2
Collecting mt2
  Using cached mt2-0.1.4.tar.gz (17 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/wfawcett/opt/anaconda3/bin/python /Users/wfawcett/opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/tg/d7mypqb95lz0r1wrdbxqbs840000gn/T/pip-build-env-5ercqndn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'pybind11>=2.6.0'
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Users/wfawcett/opt/anaconda3/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/wfawcett/opt/anaconda3/bin/python /Users/wfawcett/opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/tg/d7mypqb95lz0r1wrdbxqbs840000gn/T/pip-build-env-5ercqndn/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'pybind11>=2.6.0' Check the logs for full command output.
```

**Comment by kesterlester** [comment] 2021-02-10 11:17
PS to Tom: you can't complain about this one --- it's from one of your fellow anaconda users who are (consequently) always blameless.

**Comment by tpgillam** [comment] 2021-02-10 11:34
I am impressed at number of completely different ways in which installation is failing!

This suggests that if you have `enum34` installed, then that might be the cause of issues like this. I don't think this is anything that I'm responsible for:

https://github.com/iterative/dvc/issues/1582

(PS is Will on github? Would be easier if he could particpate directly :-) )

**Comment by kesterlester** [comment] 2021-02-10 11:36
Probably best Will, for you to join this discussion directly with Tom / github

https://github.com/tpgillam/mt2/issues/3

**Comment by tpgillam** [comment] 2021-02-10 11:48
( Can I tag @will-fawcett ?)

**Comment by kesterlester** [comment] 2021-02-10 11:51
Possibly. I did invite him to come here.  Don't know if that's his label, though.

**Comment by kesterlester** [comment] 2021-02-10 11:51
Oh yes, it obviously is. Do that!

**Comment by will-fawcett** [comment] 2021-02-10 11:54
Hi, yes I'm invited! I was just having a look myself to see if I could fathom out what's going on with my enum package.

**Comment by will-fawcett** [comment] 2021-02-10 11:58
FYI, I am able to install other packages via pip, e.g. `pip install pip-install-test` completed correctly.

**Comment by will-fawcett** [comment] 2021-02-10 12:05
According to this article https://stackoverflow.com/a/45716067/12479450 enum34 is depreciated since python3.6, I removed the package, and now `pip install mt2` worked correctly. 

I also tested the `mt2.get_mT2` and it calculates the value as expected.

**Comment by kesterlester** [comment] 2021-02-10 12:13
Is there any way of making the mt2 package library dependencies say "User must not have enum34 installed" ?  It would be better for the user to have the installation fail to start, for a clear reason, rather than proceed and then go wrong.  Maybe there is an unlimited number of such bans one would have to introduce though, so maybe that's not workable in the long run.

**Comment by kesterlester** [comment] 2021-02-10 12:15
Or even better would be to find a way of making this thing compile that goes no-where near fancy other packages like enum34.  Presumably there should be SOME way of saying "just compile this with minimal other packages drawin into the C++ search path ...."

**Comment by tpgillam** [comment] 2021-02-10 13:28
Thanks @will-fawcett !

@kesterlester Indeed, the potentially unbounded number of such bans seems like a good reason to not try to worry about this. I think an even stronger argument is that I do not have an explicit dependency on anything to do with enum34 - in fact it is coming from pip itself. 

I'm going to close this, as this package is not doing anything 'special' in terms of pip / enums, and sadly this problem seems to be more to do with pip itself than anything under our control here. Trying to fail more nicely would, I think, just add more complexity (and hence potential fragility).

**Closed by tpgillam** 2021-02-10 13:28 UTC
