### ISSUE TITLE
Implementation switch?

### ISSUE THREAD

**Issue by kesterlester** [tpgillam/mt2#47] opened 2021-04-28 01:07 UTC
Will Fawcett gave a short presentation in the ATLAS Susy Background forum yesterday advertising this mt2 library. There some polite interest, which is nice, with people who comments pleased to hear of (a) the vectorisation, and (b) Rupert's speedup. But there was one issue where you could hear a slight fear in the voices which concerned validation of Rupert's alg.  Bascially since atlas has used the arXiv.h code for years and years and years without change, it was clear that they were nervous about using a re-implementation even if the alg was basically the same.  I got the impression, though, that if there was a switch that would let them choose "fast_rupert" vs "as_on_arXiv" then people would then have no hurdle to adoption.

**Comment by tpgillam** [comment] 2021-04-28 10:56
It's great to hear that there's interest! 

My view in general is that @Rupt 's implementation is entirely consistent, and that we have sufficient tests to demonstrate this. If this view is not shared by users, then I think the best way forward is to add whatever tests they would like to the unit test suite such that they are happy?

Adding a switch would be very easy, but one drawback is that the low-level implementation becomes part of the public API. This makes it harder to change it in the future without breaking client code. However, your (and Colin's!) implementation *are* already built into the package, and are accessible in the private API -- i.e. a user can use this to make it easier for them to convince themselves that the public `mt2` method does the right thing, but we don't have to promise that it will work in future versions.

Concretely, a user could do what we do in our unit tests:

https://github.com/tpgillam/mt2/blob/e4381261a7c5ee3a9404059b62d2fb3187370826/tests/test_mt2_tombs.py#L8-L16

i.e. import from the `_mt2` package (which is available to all users who have installed `mt2`).

**Comment by kesterlester** [comment] 2021-04-28 11:00
I fear your reaction is too rational for ATLAS.

You should know ;) that ATLAS “conservatism” doesn’t follow the normal rules of logic.

**Comment by Rupt** [comment] 2021-04-28 11:09
Very nice to hear! For the sake of reproducibility, I think there is a rational desire for the exact same algorithm down.

I find it strange that `import mt2; _mt2.mt2_lester_ufunc` is the working way to access this. How about `import mt2; mt2.mt2_lester`?

**Comment by tpgillam** [comment] 2021-04-28 11:14
Your suggestion is to put it in the public API... which is effectively the thing that I am resisting, since once added it becomes hard to delete :-)

My hope is still that we can do whatever work is required to validate your algorithm *once*, then we can forget all about it, rather than have to support two versions ad infinitum. Baking such validation into unit tests would be even better.

**Comment by tpgillam** [comment] 2021-04-28 11:18
(The other problem I foresee is that users could start just always using the old algorithm "to be safe", and lose out on a large speedup that is in fact entirely safe. Because why would we provide the old algo in the public API if we thought the new implementation was definitely correct?)

**Comment by tpgillam** [comment] 2021-04-28 11:20
But that's more a psychological point :-) In any case, if we *have* to add it to the public API, then I prefer Rupert's suggestion (expose a new method with a suitably verbose name) rather than add a toggle to the `mt2` method.

**Comment by kesterlester** [comment] 2021-04-28 11:23
> On 28 Apr 2021, at 12:20, Tom Gillam ***@***.***> wrote:
> 
> 
> But that's more a psychological point :-) In any case, if we have to add it to the public API, then I prefer Rupert's suggestion (expose a new method with a suitably verbose name) rather than add a toggle to the mt2 method.

To be honest, that’s what I had in mind too. The point is if you can tell people that they can access an old verbosish method verbosely, they’ll be happy. They probably won’t even use it. And it can be flagged up as “documented but deprecated” in the sense that the assumption should always be that it could be removed at any release without notice.

All it would do (I think) is remove a hurdle to adoption by risk averse ATLAS people.  I don’t think it provides a long term maintenance burden.

**Comment by tpgillam** [comment] 2021-05-04 11:54
Is this sufficient? 384156e7d3c1de79b96ee666ee006e1b436f4e3a

Please close if you agree, and I'll tag a new version.

**Comment by Rupt** [comment] 2021-05-04 16:33
LGTM

**Comment by kesterlester** [comment] 2021-05-05 08:32
Concur

**Comment by Rupt** [comment] 2021-05-05 08:44
I seem to not have the power to close this issue.

**Closed** 2021-05-05 15:18 UTC

**Comment by tpgillam** [comment] 2021-05-05 15:31
646818cf1aa95b9a32126abf6582e0438648121e will release as 1.2.0, assuming the pipeline runs successfully.
